# Generated by Django 3.2.6 on 2021-08-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='date_update',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
