# Generated by Django 3.2.6 on 2021-09-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0002_auto_20210828_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_verbal',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id_question',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminer.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='id_pattern',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminer.pattern'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id_polls',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminer.polls'),
        ),
    ]
