# Generated by Django 3.2.6 on 2021-09-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0003_auto_20210911_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_verbal',
        ),
        migrations.AddField(
            model_name='question',
            name='is_verbal',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
