# Generated by Django 3.2.6 on 2021-09-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0006_auto_20210912_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPolls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_category', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminer.category')),
                ('id_polls', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminer.polls')),
            ],
            options={
                'db_table': 'category_polls',
                'managed': True,
            },
        ),
    ]
