# Generated by Django 3.2.6 on 2021-09-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0007_categorypolls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id_category',
        ),
    ]
