# Generated by Django 3.2.6 on 2021-09-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0008_remove_question_id_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='id_category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminer.category'),
        ),
    ]
