# Generated by Django 3.2.6 on 2021-09-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0009_question_id_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('id_answer', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminer.answer')),
                ('id_polls', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminer.polls')),
                ('id_question', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminer.question')),
            ],
            options={
                'db_table': 'user_answer',
                'managed': True,
            },
        ),
    ]
