# Generated by Django 3.2.6 on 2021-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0010_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='ip',
            new_name='user',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_category',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
