# Generated by Django 3.2.6 on 2021-09-20 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0011_auto_20210915_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='id_category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminer.category'),
        ),
    ]
