# Generated by Django 3.2.6 on 2021-09-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0012_useranswer_id_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer_cost',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
