# Generated by Django 3.2.6 on 2021-09-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0013_useranswer_answer_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='id_category',
            field=models.IntegerField(default=0, max_length=11),
        ),
    ]
