# Generated by Django 3.2.6 on 2021-09-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0014_alter_useranswer_id_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='id_category',
            new_name='id_category_id',
        ),
    ]
