# Generated by Django 3.2.6 on 2021-10-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0016_alter_useranswer_id_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
