# Generated by Django 3.2.6 on 2021-10-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0017_answer_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'managed': True, 'ordering': ['sort']},
        ),
        migrations.AlterField(
            model_name='pattern',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
