# Generated by Django 3.2.6 on 2021-10-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0018_auto_20211005_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
