# Generated by Django 3.2.6 on 2021-10-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0019_polls_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='sort',
        ),
        migrations.AddField(
            model_name='question',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
