# Generated by Django 3.2.6 on 2021-12-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0020_auto_20211006_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True, 'ordering': ['sort']},
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_other',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='text_other',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
