# Generated by Django 3.2.6 on 2021-12-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0021_auto_20211204_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='is_other',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='text_other',
        ),
        migrations.CreateModel(
            name='UserAnswerOther',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('other_text', models.CharField(blank=True, max_length=250)),
                ('id_question', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminer.question')),
                ('id_user_answer', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminer.useranswer')),
            ],
            options={
                'db_table': 'user_answer_other',
                'managed': True,
            },
        ),
    ]
