# Generated by Django 3.2.6 on 2021-12-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0022_auto_20211204_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswerother',
            name='id_user_answer',
        ),
    ]
